### ISSUE TITLE
Azure OCP4 DNS Connection Issues

### ISSUE THREAD

**Issue by filiy** [BCDevOps/OpenShift4-RollOut#166]
There seems to be a DNS issues where lookups intermittently fail. This is causing pod deploy and builds to sometimes fail as they can't pull images or packages as DNS resolution fails.

You can reproduce this by rsh into a pod and `watch dig google.com` and waiting for a ` ;; connection timed out; no servers could be reached` error which should not come up at all. 

- Checked resources on masters nodes but looking at top these VMs are not under load. Thinking this might be an API issue. API pods also seem to be fine.

- Deleted the pods in the openshift-dns namespace and got the daemonset to re-create in case any of the pods had issues. One of the pods had quite a few restarts: 
```
phil@c3po openshift4-azure]$ oc get pods  -n openshift-dns
NAME                READY     STATUS    RESTARTS   AGE
dns-default-4mb62   2/2       Running   2          11d
dns-default-c7skc   2/2       Running   0          14d
dns-default-gd4gj   2/2       Running   0          14d
dns-default-glmhw   2/2       Running   0          19m
dns-default-pch8l   2/2       Running   0          14d
dns-default-s2d48   2/2       Running   0          6d22h
dns-default-sn4l5   2/2       Running   43         14d
dns-default-tpj2s   2/2       Running   0          19m
dns-default-vgn4v   2/2       Running   2          11d
dns-default-vn727   2/2       Running   2          11d
dns-default-z9btg   2/2       Running   0          7d4h
```
- Checked logs on dns pods. Article: https://access.redhat.com/solutions/3804501.
```
# export PODS=`oc get pods -o=jsonpath="{.items[*].metadata.name}" -n openshift-dns`
# for pod in $PODS;do oc logs $pod -c dns -n openshift-dns &> $pod.log;done;
```
There were a few of these:
```
2020-02-09T21:58:15.084Z [ERROR] plugin/errors: 2 infogw.api.openshift.com. AAAA: read udp 10.130.4.2:40639->168.63.129.16:53: i/o timeout
```

- Thinking this could be due to the `ndots` setting in resolv.conf i tired deploying a pod with `ndots 1`
```
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: image-registry.openshift-image-registry.svc:5000/tester/nginx@sha256:063833c8d6f8ca93d0e7aeae0ab2d1cd439fb41965d27dbf1c53dce386910123
  dnsConfig:
    options:
      - name: ndots
        value: "1"
```
Still got intermittent failures. Ndots k8s dns issues detailed here: https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html and here: https://access.redhat.com/solutions/2518321

- also metric `coredns_forward_healthcheck_failure_count_total` is going up and down. Un sure about this, a few dns metrics to dig into.

- i do remember seeing something about some azure api throttling but I can't seem to track that down again.

Still investigating this one.
