### ISSUE TITLE
Automate: RBAC and Authentication

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#181]
Configure authentication and platform service RBAC setup.

- [x] Set up GitHub authentication, delete default kubeadmin
- [x] Cluster Admins, Cluster Viewers
- [x] BCDevExch Service account and "oc --as" permission setup
- [x] Restricted project/namespace creation

**Comment by j-pye** [comment]
I've been reading through the Github and IdentityProvider setup for OCP4. This might be a case where a throw away cluster would be useful for testing from scratch @filiy 
Just so i can start from nothing and test setting up auth with Github.

I was hoping the GIthub setup could be automated via the Github API but it looks like that functionality is being removed from their API in favor of the github web interface.(boo!) So it looks like part of this will be semi-manual on the github side.

Think I have the last 3 bullets sorted. Going to go with a cron job as suggested but if there is any desire for this to be an operator then I can make that work as well. :)

Also, @sbarre-esit @jefkel  are we planning to keep RBAC in https://github.com/bcgov-c/devops-platform-operations-docs/tree/master/rbac ?

**Comment by StevenBarre** [comment]
Pretty sure we can handle this with a template and some vaulted vars. See my [other docs](https://github.com/bcgov-c/advsol-docs/blob/master/OCP-4-Install.md#configure-github-auth) for the manual set of steps.

```yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github
    mappingMethod: claim
    type: GitHub
    github:
      clientID: "{{ github_clientid }}"
      clientSecret:
        name: github-oauth-app
      organizations:
      - BCDevOps
```
