### ISSUE TITLE
Decide on new values for default LimitRange

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#198]
Right now we have defaults for request/limit specified. RH recommends that we also implement maximums as well.

- https://kubernetes.io/docs/concepts/policy/limit-range/
- https://github.com/bcgov-c/platform-ops/blob/ocp4-base/ocp4/roles/quota/quotas/default-limits.yaml
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#motivation-for-default-memory-limits-and-requests

**Comment by mitovskaol** [comment]
Waiting to see if the new defaults implemented in OCP 3.11 work well and if they do, will carry them over to the new OCP 4 Platform

**Comment by StevenBarre** [comment]
What's the maximum size we want any one container to be? We probably want to set it low and encourage horizontal scaling. How about 2 CPU cores?

We can also set the mimimum PVC size to match that of what Trident supports (which is quite small)

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
      memory: 1Gi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
    max:
      cpu: 2
      memory: 8Gi
  - type: PersistentVolumeClaim
    min:
      storage: 20Mi
```

**Comment by mitovskaol** [comment]
Everything I learnt about container auto-scaling points to horizontal scaling to be a preferred way over vertical scaling. Also, the Platform resources will remain to be an issue for a while even after the OCP 4 build-out . So I am thinking let's keep the defaults and quotas to minimum and have teams come to us if they need more storage/resources. @stewartshea @jefkel what are you thoughts about this?

**Comment by jefkel** [comment]
#### CPU and Memory Pod Maximums

There are some default maximums in place already (through namespace quotas), and my initial instinct is that if we are going to set a Max Pod resource limit, it should be as a percentage of the quota (ie: do we want to allow a team to consume 100% of it's quota in a single pod? 2 pods? should be pretty lenient)  

We need to be careful about setting low _limit maximums_ as it's not just for deployments, but also will impact other pod resources as well (builds/crons/etc) that may require larger spike workload.  The point is not to restrict/control developers to **"Do it our way"**, but rather to allow development teams to learn/develop their own, and we guide them towards improvement.  Default Requests, Default Limits are great "safety rails" for teams that don't harm teams ability to move forward (they can override these with more appropriate values as they need).  Restricting the maximum pod resources will create a design barrier, not a safety rail.

Too many restrictions that require escalation and platform services intervention to resolve will drive support time up, and we don't want to end up with so many rules that every project definition becomes a list of exceptions.

#### Storage Minimums

I'm happy to reduce the minimum PVC request size.  Keeping the PVC quotas the same will be enough to encourage better behaviour (like using configmaps instead of PVC's to hold configuration information, etc...)

**Comment by StevenBarre** [comment]
We are deciding against setting maximums for pod resources. And will implement the minimum PVC size.

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
      memory: 1Gi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
  - type: PersistentVolumeClaim
    min:
      storage: 20Mi
```
