### ISSUE TITLE
Aporeto - Intermittent Build Issue (SPIKE)

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#339]
**Describe the issue**
With Aporeto Enforcers enabled in OpenShift 4, builds are failing intermittently during the `git clone`when the `git-clone` init container starts. 

One of the following error messages occur during a build failure:
- Could not resolve host: github.com; Unknown error
- error: RPC failed; result=6, HTTP code = 0

**Which Sprint Goal is this issue related to?**
Aporeto Implemented and Tested in KLAB/CLAB"

**Definition of done Checklist (where applicable)**
- [x] Build issue solution implemented and tested

**Comment by j-pye** [comment]
**Update on Aporeto: **
I tested builds with and without the suggested workaround from Julian (PodInjectorSelector) in KLAB.
11/100 Builds Failed without the PodInjectorSelector
0/200 Builds Failed with the PodInjectorSelector

This issue is also present in CLAB (Thetis) so I have another set of tests running there just to confirm there's no remaining build issues.

Using the `PodInjectorSelector` does increase the Pod Container Count by 1, and adds up to 30 seconds (observed) to the build time when the container image for the aporeto init container has to be pulled.

**Comment by j-pye** [comment]
CLAB Tests
9/100 Builds Failed without the PodInjectorSelector
0/200 Builds Failed with the PodInjectorSelector

KLAB Tests - Round 2
20/200 Builds Failed without the PodInjectorSelector
0/200 Builds Failed with the PodInjectorSelector 

Based on these results these are my current action items:
- Inform Aporeto/PANW the workaround is working and confirm this is their recommendation to proceed until we migrate to Prisma Cloud
- Discuss Implementation Options with team

Suggested Implementation Options:
- Implement PodInjectorSelector for Builds in the Project Provisioning Templates - Estimate 1 hour
- Implement PodInjectorSelector into the Operator to allow teams to self serve, and resolve non-build pod network startup issues, if needed. - Estimate 2 hours

**Comment by j-pye** [comment]
I'm thinking that applying these through project provisioning will be the best solution. Least effort, allows for self serve, and it's easy to remove or update via GitOps. I've also reached out to Julian for input. He sent me the following docs and is working on getting me the technical details of what exactly the aporeto init container is doing and what it has access to.

Docs:
https://docs.aporeto.com/3.14/setup/k8s-crds/#use-pod-injector-selectors-for-more-security
https://docs.aporeto.com/saas/reference/components/operator/#aporeto-io-inject

Builds - Tools NS
```yaml
- apiVersion: k8s.aporeto.io/v1beta1
  kind: PodInjectorSelector
  metadata:
    name: builds
  spec:
    options:
      image: aporeto/aporeto-init-waitforpu:release-3.14.5
      imagePullPolicy: IfNotPresent
      warnOnlyTimeoutSeconds: 3
    selector:
      matchExpressions:
      - key: openshift.io/build.name
        operator: Exists
```
Generic - deployed to all NS for optional use
```yaml
- apiVersion: k8s.aporeto.io/v1beta1
  kind: PodInjectorSelector
  metadata:
    name: zero-trust-first
  spec:
    options:
      image: aporeto/aporeto-init-waitforpu:release-3.14.5
      imagePullPolicy: IfNotPresent
      warnOnlyTimeoutSeconds: 3
    selector:
      matchLabels:
        zero-trust-first: true
 ```

This requires teams to add the `zero-trust-first: true` label to their non-build pods but also gives them a way to opt-out if they don't want it for whatever reason. 

Thoughts? @stewartshea @jefkel @sbarre-esit
