### ISSUE TITLE
Create bcgov namespace on all clusters

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#366]
Platform Services would like to store any bespoke images in a namespace (repo) separate from the `openshift` namespace. Please create a `bcgov` namespace on all clusters with sufficient access control so that all teams can read (images and/or templates) from the namespace.

**Comment by StevenBarre** [comment]
Created the following on KLAB and Silver by hand.

```yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      openshift.io/description: Shared Custom Images and Templates
      openshift.io/display-name: bcgov
    labels:
      category: venture
      environment: prod
      product: bcgov
      project_type: user
      team: DevOps
    name: bcgov
- apiVersion: authorization.openshift.io/v1
  kind: Role
  metadata:
    name: shared-resource-viewer
    namespace: bcgov
  rules:
  - apiGroups:
    - ""
    - template.openshift.io
    attributeRestrictions: null
    resources:
    - templates
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreamimages
    - imagestreams
    - imagestreamtags
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreams/layers
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: shared-resource-viewer
    namespace: bcgov
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: shared-resource-viewer
  subjects:
  - kind: Group
    name: system:authenticated
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: admin
    namespace: bcgov
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - kind: ServiceAccount
    name: bcdevops-admin
    namespace: openshift
```

Moving to blocked until CCM is ready to take this task on for us.
