### ISSUE TITLE
Create ObjectStorage access for migration tool (CAM)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#377]
**Describe the issue**
The RH Cluster Application Migration tool (CAM) uses an object storage bucket to transfer object manifests and state files between clusters.  An object bucket and bucket user are required to test the objectstore service (instead of standing up a temporary service)

**Which Sprint Goal is this issue related to?**
Configuring Application Migration tools

**Definition of done Checklist (where applicable)**
- [x] Bucket user/token available as a secret in the klab openshift-migration namespace
- [x] access to bucket using the above user/token confirmed within CAM application.

**Comment by caggles** [comment]
all done, the secret is called cam-objectstore!

**Comment by jefkel** [comment]
Updated the secret with missing detail:
``` yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cam-objectstore
data:
  accesskey: <username>
  bucketname: <bucketname>
  s3endpoint: <endpoint URL>
  secretaccesskey: <token/password>
```
