### ISSUE TITLE
Burn in test of Silver NetApp

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#382]
**Describe the issue**
We need to do some performance and stability testing of the Silver NetApp prior to the Oct 14 go-live.

**Which Sprint Goal is this issue related to?**
TBD

**Additional context**
Create a StatefulSet to launch a pod on each node with a NFS (and then block volume) and run `dd if=/dev/urandom of=/test/a.bin bs=1M count=10240` and attempt to saturate the links. Have the pods restart once done to keep the pressure up.

Have network team pull some cords from servers and from the NetApp to see how failover works and if any of the pods hang or die due to storage issues.

**Definition of done Checklist (where applicable)**
- [x] Document peak load on NetApp
- [x] Document what happens in a failure of a server link
- [x] Document what happens in a failure of a netapp link

**Comment by StevenBarre** [comment]
Ran a load test and saturated the 10G port on the NetApp.

Scheduled a failure test with DCM for Oct 9th @13:00

**Comment by StevenBarre** [comment]
With the help of DCM we pulled the active cable from a servers bond and it failed over in 200ms as expected. No noticeable impacts to the speed of I/O other than the short pause while the failover occurred. Traffic routed through the the secondary switch, to the core, and back to the primary switch and onto the NetApp.

DCM then pulled the primary cable from the NetApp. The NetApp switched traffic over to the secondary interface and sent an alert to Storage team. Traffic routed through the the secondary switch, to the core, and back to the primary switch and onto the server.

Storage Team then performed a shutdown on the primary NetApp node. This was the most disruptive to storage traffic and caused about a 60s window of instability as the secondary NetApp detected the issue and took over the IPs. I/O resumed after in the pods without issue though.

**Comment by StevenBarre** [comment]
File stress test job. This creates up to 10 pods in parallel writing a 10GB file and then checksumming it. As the pod finishes a new one is created by the job. Up to 1000 pods will run in total unless you delete the job sooner. Multiple sets of the job can be created to generate higher load.
```yaml
apiVersion: v1
kind: Template
metadata:
  name: stress-template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "job-data-${NUMBER}"
    namespace: stress-test
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 150Gi
    storageClassName: netapp-file-standard
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: "stress-test-job-${NUMBER}"
    namespace: stress-test
  spec:
    backoffLimit: 6
    completions: 1000
    parallelism: 10
    template:
      metadata:
        name: "stress-test-job-${NUMBER}"
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - |
            sleep $[($RANDOM % 30) + 30]s
            dd if=/dev/urandom of=/data/${HOSTNAME}.bin bs=1M count=10240
            md5sum /data/${HOSTNAME}.bin
            rm -f /data/${HOSTNAME}.bin
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          imagePullPolicy: IfNotPresent
          name: stress-test-job
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "job-data-${NUMBER}"
parameters:
- description: Number
  name: NUMBER
  required: true
```

**Comment by StevenBarre** [comment]
Similar idea, but with block storage. Can't be run in parallel due to how iscsi works. Just run more jobs to get more parallelism. Also uses smaller files and PVC to cause pods to restart more often, as iscsi mounting is a larger issue than NFS.
```yaml
apiVersion: v1
kind: Template
metadata:
  name: stress2-template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "job-data2-${NUMBER}"
    namespace: stress-test
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: netapp-block-standard
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: "stress2-test-job-${NUMBER}"
    namespace: stress-test
  spec:
    backoffLimit: 6
    completions: 1000
    parallelism: 1
    template:
      metadata:
        name: "stress2-test-job-${NUMBER}"
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - |
            sleep $[($RANDOM % 30) + 30]s
            dd if=/dev/urandom of=/data/${HOSTNAME}.bin bs=1M count=1024
            md5sum /data/${HOSTNAME}.bin
            rm -f /data/${HOSTNAME}.bin
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          imagePullPolicy: IfNotPresent
          name: stress2-test-job
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "job-data2-${NUMBER}"
parameters:
- description: Number
  name: NUMBER
  required: true
```
