### ISSUE TITLE
Document NSP Operator Changes

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#384]
**NSP Operator Changes requiring documentation:**
- CRD ApiVersion changed from 
     `apiVersion: security.developer.gov.bc.ca/v1alpha1`
      to
     `apiVersion: security.devops.gov.bc.ca/v1alpha1`
- External Networks CRs no longer support `ports` and `protocols`, the two fields have been combined into `servicePorts`. 

**DoD:**
- [x] Update Developer Documentation with CRD API Version Changes
- [ ] Update Developer Documentation with External Network CR(D) Changes.
- [ ] Update Developer Documentation with PodInjectorSelector information

**Additional Information:**
https://docs.aporeto.com/saas/release-notes/20200915/
https://docs.aporeto.com/saas/release-notes/20191008/#define-the-protocols-and-ports-of-external-networks-as-pairs

The primary reason for the move to servicePorts is because of the last line in the following text. 
```
All protocols must share the same port or set of ports. For example, you can set a ServicePorts value of [tcp/80,udp/80] but not [tcp/80,udp/90]. We will lift this restriction in a future release.
```
We will be doing testing to see if the restriction has already been lifted but if it hasn't we will still be prepared for when it is without requiring another breaking change after going to production. If the restriction is still in place this will need to be added to the developer documentation.

**Comment by StevenBarre** [comment]
Can we add to the DoD?

- Update Developer Documentation with PodInjectorSelector information

Projects will come with one for Builds by default, but devs may want to add their own in addition.

**Comment by j-pye** [comment]
For those in KLAB:
There are 2 scenarios:
- Network connectivity must not break
1. Write open NSP policies with the new CR ApiVersion -- Be sure to use a unique `metadata.name` that's not the same as any of your existing NSPs on the old CR ApiVersion
2. `oc apply -f <new nsp | new en>`
3. `oc delete -f <old nsp / old en>` that are currently in place.
4. Update the old files with the new CR ApiVersion and Update your external networks if you have any
5. `oc apply -f <updated nsp | updated en>`
6. Delete the Open Policies we created in Step 1 and 2.

- Network connectivity can break
1. `oc delete -f <nsp / en>` that are currently in place.
2. Replace the CR ApiVersion with the new one. 
3. Update any External Networks to use `servicePorts`
4. `oc apply -f <nsp | en>`

Example External Network:
Before:
```
apiVersion: security.developer.gov.bc.ca/v1alpha1
kind: ExternalNetwork
metadata:
  name: bla-bla1
spec:
  description: |
    specify a custom external network that can be
    referenced by name.
  entries:
  - 0.0.0.0/0
  protocols:
  - tcp
  ports:
  - "80"
  - "443"
```
After:
```
apiVersion: security.devops.gov.bc.ca/v1alpha1
kind: ExternalNetwork
metadata:
  name: bla-bla1
spec:
  description: |
    specify a custom external network that can be
    referenced by name.
  entries:
  - 0.0.0.0/0
  servicePorts:
  - tcp/80
  - tcp/443
```
