### ISSUE TITLE
Monitor Aporeto Enforcer health

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#474]
**Describe the issue**
Related to [Discuss Alternatives for Handling Aporeto Failure](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/261).

We need to alert on-call should a node no longer be able to enforce network security.

**Which Sprint Goal is this issue related to?**
SG - Sprint 21 Platform Operations

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Determine what qualifies as healthy / unhealthy
  - For this ticket, we're just going to use the built in AlertManager rules
- [x] Create monitor in KLAB and test
- [ ] Create PR for needed code
- [ ] Deploy to SILVER

**Comment by StevenBarre** [comment]
@j-pye how hard would it be to rename the enforcer namespace? Then we could take advantage of a bunch of the built in alerting rules like https://console.apps.silver.devops.gov.bc.ca/monitoring/alertrules/2079999808

**Comment by StevenBarre** [comment]
Here's the pre-build alerting rules I'm hoping to leverage.

```
alert: KubePodCrashLooping
expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}[15m])
  * 60 * 5 > 0
for: 15m
labels:
  severity: warning
annotations:
  message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }})
    is restarting {{ printf "%.2f" $value }} times / 5 minutes.
```

```
alert: KubePodNotReady
expr: sum
  by(namespace, pod) (max by(namespace, pod) (kube_pod_status_phase{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)",phase=~"Pending|Unknown"})
  * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (1, max by(namespace,
  pod, owner_kind) (kube_pod_owner{owner_kind!="Job"}))) > 0
for: 15m
labels:
  severity: warning
annotations:
  message: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state
    for longer than 15 minutes.
```

```
alert: KubeDaemonSetRolloutStuck
expr: kube_daemonset_status_number_ready{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}
  / kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}
  < 1
for: 15m
labels:
  severity: warning
annotations:
  message: Only {{ $value | humanizePercentage }} of the desired Pods of DaemonSet
    {{ $labels.namespace }}/{{ $labels.daemonset }} are scheduled and ready.
```

```
alert: KubeDaemonSetNotScheduled
expr: kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}
  - kube_daemonset_status_current_number_scheduled{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}
  > 0
for: 10m
labels:
  severity: warning
annotations:
  message: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset
    }} are not scheduled.'
```

```
alert: KubeDaemonSetMisScheduled
expr: kube_daemonset_status_number_misscheduled{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}
  > 0
for: 15m
labels:
  severity: warning
annotations:
  message: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset
    }} are running where they are not supposed to run.'
```

As they are all `severity: warning` we'll need some routing in Alertmanager to direct these alertnames in those namespaces to the on-call handler.
